### ISSUE TITLE
Acronym “NLE” (Non-Linear Editor) used without definition or examples

### ISSUE THREAD

**Issue by arrowtype** [goodhertz/coldtype-examples#3]
From the last line of the [current readme](https://github.com/goodhertz/coldtype-examples/tree/6b757d96afeab798bf9291b7abd58d0b12864552):

> Once you do a `ra` command, you can import those frames into any NLE in order to see the actual animation in realtime.

NLE seems to mean [Non-linear Editor](https://en.wikipedia.org/wiki/Non-linear_editing_system#:~:text=A%20non%2Dlinear%20editing%20system,video%20editing%20and%20film%20editing.), but as an outsider to video editing, this is the first time I’ve heard the term. 

Maybe it could link to the definition? Or, probably better, it could just provide a couple of examples:

> Once you do a `ra` command, you can import those frames into any NLE (e.g. Adobe Premiere, Apple Final Cut Pro, etc) in order to see the actual animation in realtime.

It would also be awesome if that process was described or linked to, but I realize that is a bigger ask, and may not be what you want to use this repo for.

**Comment by stenson** [comment]
Sorry I didn't see this issue until now! Not sure why I wasn't getting notifications — anyway because of the general shift in Coldtype to have an integrated GL window, you can now preview animations in the app itself by hitting spacebar. I've updated the docs to reflect that. I totally agree that NLE is a bit obscure, so probably better just to avoid it in general.

All that said, easy integration with NLEs is still a major feature of coldtype, and I'll definitely be doing some video tutorials on that.
